version: "2.0"

services:
  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: logstash:latest
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    environment:
      - LOGSPOUT=ignore
    ports:
      - "5000:5000"
    links:
      - elasticsearch
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    links:
      - elasticsearch
  logspout:
    build: ./logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - logstash
    environment:
      - ROUTE_URIS=logstash://logstash:5000
  nagios:
    image: quantumobject/docker-nagios
    ports:
      - 8080:80
